### ISSUE TITLE
errors while installing requirements.txt

### ISSUE THREAD

**Issue by mriyank** [maelfabien/Multimodal-Emotion-Recognition#10]
Hi, great repository, I'm facing issues while installing the requirements.txt on my device. please help me fix this 
![image](https://user-images.githubusercontent.com/48956758/93747193-fb5d5f00-fc13-11ea-8f4e-619fb1802b84.png)

**Comment by L5mp** [comment]
Same...

**Comment by DeivisDervinis** [comment]
I managed to get it running by editing the requirements file up to date.

`requirements.txt`
```Flask
Gunicorn
Werkzeug
numpy==1.18.5
pandas
opencv-python
cmake
argparse
scipy
dlib
tensorflow
imutils
tika
wave
nltk
gensim
seaborn
scikit-learn
dill
keras
wordcloud
pandas
argparse
scipy
dlib
tensorflow
imutils
```
